In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import confusion_matrix, accuracy_score
from tabulate import tabulate
from sklearn.preprocessing import MinMaxScaler
from sklearn import tree
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [10]:
df=pd.read_csv(r"C:\Users\kirut\Downloads\Paper1\bank.csv",sep=";")

In [11]:
df

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed    y  
0           5191.0   no  
1           5191.0   no  
2           5191.0   no  
3           5191.0   no  
4           5191.0   no  
...            ...  ...  
41183       4963.6  yes  
41184       4963.6   no  
41185       4963.6   no  
41186       4963.6  yes  
41187       4963.6   no  

[41188 rows x 21 columns]

In [12]:
df.age.unique()

array([56, 57, 37, 40, 45, 59, 41, 24, 25, 29, 35, 54, 46, 50, 39, 30, 55,
       49, 34, 52, 58, 32, 38, 44, 42, 60, 53, 47, 51, 48, 33, 31, 43, 36,
       28, 27, 26, 22, 23, 20, 21, 61, 19, 18, 70, 66, 76, 67, 73, 88, 95,
       77, 68, 75, 63, 80, 62, 65, 72, 82, 64, 71, 69, 78, 85, 79, 83, 81,
       74, 17, 87, 91, 86, 98, 94, 84, 92, 89], dtype=int64)

In [13]:
df.job.unique()

array(['housemaid', 'services', 'admin.', 'blue-collar', 'technician',
       'retired', 'management', 'unemployed', 'self-employed', 'unknown',
       'entrepreneur', 'student'], dtype=object)

In [14]:
df['emp.var.rate'].unique()

array([ 1.1,  1.4, -0.1, -0.2, -1.8, -2.9, -3.4, -3. , -1.7, -1.1])

In [15]:
df['cons.price.idx'].unique()

array([93.994, 94.465, 93.918, 93.444, 93.798, 93.2  , 92.756, 92.843,
       93.075, 92.893, 92.963, 92.469, 92.201, 92.379, 92.431, 92.649,
       92.713, 93.369, 93.749, 93.876, 94.055, 94.215, 94.027, 94.199,
       94.601, 94.767])

In [16]:
df["y"].value_counts()

no     36548
yes     4640
Name: y, dtype: int64

In [17]:
df.replace('unknown',np.NaN,inplace=True)

In [18]:
y1 = df['y']


In [19]:
df.drop(["duration"] , axis=1,inplace=True)
df.isnull().sum()

age                  0
job                330
marital             80
education         1731
default           8597
housing            990
loan               990
contact              0
month                0
day_of_week          0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
dtype: int64

In [20]:
df1 = pd.get_dummies(df)
df1.head()

age  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0   56         1    999         0           1.1          93.994   
1   57         1    999         0           1.1          93.994   
2   37         1    999         0           1.1          93.994   
3   40         1    999         0           1.1          93.994   
4   56         1    999         0           1.1          93.994   

   cons.conf.idx  euribor3m  nr.employed  job_admin.  ...  day_of_week_fri  \
0          -36.4      4.857       5191.0           0  ...                0   
1          -36.4      4.857       5191.0           0  ...                0   
2          -36.4      4.857       5191.0           0  ...                0   
3          -36.4      4.857       5191.0           1  ...                0   
4          -36.4      4.857       5191.0           0  ...                0   

   day_of_week_mon  day_of_week_thu  day_of_week_tue  day_of_week_wed  \
0                1                0                0                0   
1                1                0                0                0   
2                1                0                0                0   
3                1                0                0                0   
4                1                0                0                0   

   poutcome_failure  poutcome_nonexistent  poutcome_success  y_no  y_yes  
0                 0                     1                 0     1      0  
1                 0                     1                 0     1      0  
2                 0                     1                 0     1      0  
3                 0                     1                 0     1      0  
4                 0                     1                 0     1      0  

[5 rows x 58 columns]

In [21]:
from sklearn.tree import DecisionTreeClassifier
    
def convert_cats(df,cols):
  for i in cols:
    df[i] = df[i].astype("category").cat.codes
  return df



In [22]:
def fillMissing(missing_cols , df):

  df1=df.copy()
  for col in missing_cols:
    df1=convert_cats(df1,['job','marital','education','loan','contact','month','poutcome','y',"default" ,"housing","day_of_week"])
    test=df1[df1[col]==-1]
    train=df1[df1[col]!=-1]
    tree=DecisionTreeClassifier()
    tree.fit(train.drop(col,axis=1),train[col])
    test.loc[:,col]=tree.predict(test.drop(col,axis=1))
    df1 = train.append(test)
    df1.replace(-1,np.NaN,inplace=True)
  
  return df1  

In [23]:
df1 = fillMissing(["job" , "marital","education","loan","default" ,"housing"],df.copy())
df1.shape

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .

(41188, 20)

In [24]:
cat_cols = ['job','marital','education','loan','contact','month','poutcome',"day_of_week","default" ,"housing" ]

for col in cat_cols:
    df1 = df1.join(pd.get_dummies(df1[col],prefix = col))

keep = [col for col in df1.columns if col not in cat_cols]
df1 = df1 [keep]

In [25]:
df1["y"]=df1.y.astype('category')
df1["y"]=df1["y"].cat.codes

In [26]:
cols = df1.columns.values.tolist()
y=df1['y']
X = df1[[col for col in cols if col !="y"]]
X.shape ,y.shape

((41188, 56), (41188,))

In [27]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

LOGISTICAL REGRESSION

In [28]:
model = LogisticRegression()
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
predict = model.predict(X_test)

In [30]:
predict

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [31]:
Log = mean_squared_error(y_test, predict, squared=False)

In [32]:
Log

0.3202077095571759

<h1>DECISION TREE</h1>

In [33]:
modeldtr = tree.DecisionTreeRegressor(random_state=42)
modeldtr.fit(X_train,y_train)

DecisionTreeRegressor(random_state=42)

In [34]:
predictdtr = modeldtr.predict(X_test)

In [35]:
dec=mean_squared_error(y_test, predictdtr, squared=False)

<h1>RANDOM FOREST

In [36]:
regressor = RandomForestRegressor(max_depth=2,random_state=42)
regressor.fit(X_train,y_train)

RandomForestRegressor(max_depth=2, random_state=42)

In [37]:
regressor.predict(X_test)

array([0.05491354, 0.36633664, 0.05491354, ..., 0.05491354, 0.05491354,
       0.20375113])

In [38]:
regressor.score(X_test,regressor.predict(X_test))

1.0

In [39]:
reg=mean_squared_error(y_test,regressor.predict(X_test),squared=False)

<h1>ADA BOOSTING

In [40]:
reg = AdaBoostRegressor(n_estimators=100, random_state=42)
reg.fit(X_train,y_train)

AdaBoostRegressor(n_estimators=100, random_state=42)

In [41]:
lmn=reg.score(X_test,y_test)

In [42]:
lmn

0.20235437685283875

<h1>NAivES BAYES

In [43]:
gnb = GaussianNB()

In [44]:
gnb.fit(X_train, y_train)

GaussianNB()

In [45]:
 y_pred = gnb.predict(X_test)

In [46]:
nav=metrics.accuracy_score(y_test,y_pred)

<h1>SVM

In [47]:
from sklearn import svm
clf = svm.SVC(kernel='linear') # Linear Kernel
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
clf.score(X_test,y_test)

0.8916403657845755

In [48]:
svm=metrics.accuracy_score(y_test, y_pred)

<h1>KNN

In [50]:
score1=[]
model = KNeighborsClassifier(n_neighbors=1)
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
score1.append(model.score(X_test,y_test))

In [51]:
knn=max(score1)

In [52]:
gr=[Log,lmn,knn,svm]
name=['logistical regression','ADA BOOSTING REGRESSION','kNN','SVM']

In [53]:
table = [['logistical regression',Log],['ADA BOOSTING REGRESSION',lmn],['KNN',knn],['SVM',svm]]
print(tabulate(table))

-----------------------  --------
logistical regression    0.320208
ADA BOOSTING REGRESSION  0.202354
KNN                      0.847698
SVM                      0.89164
-----------------------  --------


In [54]:
print(name[gr.index(max(gr))]," IS THE FIT!!!!!!")

SVM  IS THE FIT!!!!!!
